default_dependencies: false
cli: dexter
targets:
  ubuntu-16.04:
    dependencies:
      - libpq5
  ubuntu-14.04:
    dependencies:
      - libpq5
  debian-8:
    dependencies:
      - libpq5
  centos-7:
    dependencies:
      - postgresql-libs
  sles-12:
    dependencies:
      - postgresql93
