default_dependencies: false
cli: dexter
targets:
  ubuntu-22.04:
    dependencies:
      - libpq5
      - libssl3
  ubuntu-20.04:
    dependencies:
      - libpq5
      - libssl1.1
  debian-11:
    dependencies:
      - libpq5
      - libssl1.1
