default_dependencies: false
cli: dexter
targets:
  ubuntu-20.04:
    dependencies:
      - libpq5
      - libssl1.1
  ubuntu-18.04:
    dependencies:
      - libpq5
      - libssl1.0.0
  ubuntu-16.04:
    dependencies:
      - libpq5
      - libssl1.0.0
  ubuntu-14.04:
    dependencies:
      - libpq5
      - libssl1.0.0
  debian-10:
    dependencies:
      - libpq5
      - libssl1.1
  debian-9:
    dependencies:
      - libpq5
      - libssl1.0.2
  debian-8:
    dependencies:
      - libpq5
      - libssl1.0.0
  centos-8:
    dependencies:
      - postgresql-libs
  centos-7:
    dependencies:
      - postgresql-libs
  sles-12:
    dependencies:
      - postgresql93
