default_dependencies: false
cli: dexter
targets:
  ubuntu-24.04:
    dependencies:
      - libpq5
      - libssl3
  ubuntu-22.04:
    dependencies:
      - libpq5
      - libssl3
  debian-12:
    dependencies:
      - libpq5
      - libssl3
  debian-11:
    dependencies:
      - libpq5
      - libssl1.1
